spring:
    profiles: development
    messages:
        cache-seconds: -1
    datasource:
        platform: oracle
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@127.0.0.1:1521:xe
        username: system
        password: oracle
    session:
        jdbc:
            # spring-session-jdbcに必要なテーブルを作成する
            schema: classpath:org/springframework/session/jdbc/schema-oracle.sql
    resources:
        # キャッシュの無効化
        cache-period: 0
flyway:
    enable: true
    baseline-on-migrate: true
doma:
    # SQLファイルをキャッシュしない
    sql-file-repository: no_cache
logging:
    level:
        org.springframework: INFO
        org.springframework.jdbc: INFO
        org.thymeleaf: DEBUG
        com.sample: DEBUG

####
# アプリケーションの設定
application:
    fileUploadLocation: build/sample
    cors:
        allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, X-XSRF-TOKEN"
        allowedMethods: "POST, GET, PUT, OPTIONS, DELETE"
        allowedOrigins: "*" # CORSを許可するドメイン名を指定する
